bootstrap_cmds:
  - /usr/local/bin/python3.7 -m venv env
  - . ./env/bin/activate
  - pip install --upgrade pip  
  - pip install -r requirements.txt 
  - deactivate
env:
  FLASK_APP: app.py
  PORT: 8080
launch_cmds:
  - . ./env/bin/activate
  - flask run --host=0.0.0.0 --port=$(($PORT + $PLCLI_INSTANCE_ID))
